version: "3"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    container_name: zookeeper
    networks:
      - broker-kafka
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:6.2.0
    container_name: kafka
    networks:
      - broker-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9101:9101"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://127.0.0.1:9092
      # KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT 
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      # KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      # KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  kafdrop:
    image: obsidiandynamics/kafdrop:3.27.0
    networks:
      - broker-kafka
    depends_on:
      - kafka
      - zookeeper
    ports:
      - 19000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:29092
      

  producer:
    container_name: producer
    build:
      context: ./producer
      dockerfile: Dockerfile
    environment:
      - KAFKA_TOPIC_NAMES=Sensor_Road1,Sensor_Road2,Sensor_Road3
      - KAFKA_SERVER=kafka
      - KAFKA_PORT=29092
    ports:
      - 8000:8000
    restart: "always"
    depends_on:
      - kafka  
    networks:
      - broker-kafka
      
  consumer_0:
    container_name: consumer_0
    build:
      context: ./consumers/consumer_0
      dockerfile: Dockerfile
    environment:
      - KAFKA_TOPIC_NAME=Sensor_Road1
      - KAFKA_SERVER=kafka
      - KAFKA_PORT=29092
    ports:
      - 8010:8010
    restart: "always"
    depends_on:
      - zookeeper
      - kafka
      - producer
    networks:
      - broker-kafka  
      - default
      
  consumer_1:
    container_name: consumer_1
    build:
      context: ./consumers/consumer_1
      dockerfile: Dockerfile
    environment:
      - KAFKA_TOPIC_NAME=Sensor_Road2
      - KAFKA_SERVER=kafka
      - KAFKA_PORT=29092
    ports:
      - 8011:8011
    restart: "always"
    depends_on:
      - zookeeper
      - kafka
      - producer
    networks:
      - broker-kafka  
      - default
      
  consumer_2:
    container_name: consumer_2
    build:
      context: ./consumers/consumer_2
      dockerfile: Dockerfile
    environment:
      - KAFKA_TOPIC_NAME=Sensor_Road3
      - KAFKA_SERVER=kafka
      - KAFKA_PORT=29092
    ports:
      - 8012:8012
    restart: "always"
    depends_on:
      - zookeeper
      - kafka
      - producer
    networks:
      - broker-kafka  
      - default
      
networks:
  broker-kafka:
    driver: bridge
 
